### ISSUE TITLE
Deleted account entries in DynamoDB are strangely brought back

### ISSUE THREAD

**Issue by danielkoo** [newscorpaus/consigliere#11]
e.g. if I delete an account in the consigliere table in DynamoDB, after some time is passed it will reappear again.

This causes issues where an old account is breaking Consigliere, but as we cannot permanently delete it from the DB it will come back and keep breaking the app (which is a separate bug)

**Comment by ivarrian** [comment]
Does it reappear in the Dynamo table or just in the UI? If it's the UI, my guess is the deletion is probably not cascading through and ridding Redis of all key-vals related to that account. If it actually reappears in the Dynamo table, that is an extremely weird one.

**Comment by danielkoo** [comment]
hey @ivarrian 
When the account is removed via the UI, I see the entry being deleted from the table, but some time later it does get re-added to the table!
I've even removed all Redis entries with that account ID as the prefix, in case Consigliere was using it to reconstruct the account details, but that doesn't look to be the case as it didn't make a difference.

**Comment by danielkoo** [comment]
I am beginning to guess it might be due to the statfetcher being a long-running process, and it's probably cached all the accounts when it was started up. With no explicit purging/reloading of the accounts when an account is removed, I am guessing it just adds the account back in when it runs on the hour.

**Comment by danielkoo** [comment]
Yep, I'm fairly certain the statsfetcher restores the table to the list of accounts it first cached when Consigliere was started; any deletions that we do will be reverted when it does the stats-gathering (on the hour).
I verified this by firstly setting the statsfetcher to run every minute so I don't have to wait too long, and then:

1. deleting account A
2. stopping Consigliere, making sure it was between stats runs and that the account is really gone in Dynamo
3. starting Consigliere back up
4. deleting account B
5. and wait for the statsfetcher to run, and putting the account B back into Dynamo
6. I can also verify account A is not brought back any more.

**Comment by danielkoo** [comment]
Given scheduler.js creates a cron job for every account, the best way in which we can solve this is to target the cron jobs, probably something like the following:
keep a list of cron jobs mapped to the account IDs, and on the deletion of an account, stop that corresponding cron job and also remove it from the list

In the meantime, the steps above can serve as a workaround.
