### ISSUE TITLE
after initial setup and run, seeing the following error "Error on redis connection | ReplyError: ERR invalid DB index"

### ISSUE THREAD

**Issue by dhsu70** [newscorpaus/consigliere#26]
on initial setup, I have run into the following error in the statfetcher.log:
{"level":"error","message":"DataStore/Redis | Error on redis connection | ReplyError: ERR invalid DB index","timestamp":"2017-04-28T20:29:16.046Z"}

the webpage starts up but is blank aside from a github icon and link to this repo.

I have an AWS account configured with full dynamodb access, but the table itself is empty.
redis-cli does allow me to connect but when I enter dbsize, it returns 0.

is there a step missing about the initial data population/configuration?

after the npm install and npm start, I noticed that the variables defined in create_table.sh did not match what I saw in dynamodb.  I deleted the table and ran the create_table.sh script and it set the provisioned read and write capacity properly that time (I edited the script to do this in my AZ since the default there is listed as ap-southeast-2).  I continue to get the invalid DB index error since both dynamodb and redis db are empty.  

Did I miss a step or config somewhere?

**Comment by PabloCastellano** [comment]
I'm actually facing the same issue. Did you finally solve it?

**Comment by felclef** [comment]
About the Redis connection, what I found from the code[1] is that the URL is parsed and needs to be in the format:

```
// [redis:]//[[user][:password]@][host][:port][/db-number][?db=db-number[&password=bar[&option=value]]]
```

So, you should use something like:

```
export REDIS_URL=redis://your-redis-dns:6379/1
```

Using the db-index 1 in the example. 

--
About the blank screen, I found that the install could not prepare the assets [2]. So, from all the install warnings, I found that the `ugglyfyjs` has changed its name to `uggyfy-js`. Yeah...

I changed it on the `package.js`, both dependencies and postinstall [3]. Then, `npm install` it again...

My patch after the changes, including DDB region:
```
diff --git a/package.json b/package.json
index ea9448a..4484b6f 100644
--- a/package.json
+++ b/package.json
@@ -10,7 +10,7 @@
     "test": "NODE_CONFIG_DIR='./src/config' gulp test",
     "start": "export NODE_CONFIG_DIR='./src/config' ; node_modules/forever/bin/forever start -a -l /var/log/consigliere/forever.log -o /var/log/consigliere/forever.out.log -e /var/log/consigliere/forever.err.log src/index.js",
     "refresh_cache": "NODE_CONFIG_DIR='./src/config' node src/tools/refresh_cache.js",
-    "postinstall": "mkdir -p src/public/scripts; node_modules/bower/bin/bower install; node_modules/browserify/bin/cmd.js src/react/app.js -t [ babelify --presets [ es2015 react ] ] | node_modules/uglifyjs/bin/uglifyjs > src/public/scripts/bundled.js"
+    "postinstall": "mkdir -p src/public/scripts; node_modules/bower/bin/bower install; node_modules/browserify/bin/cmd.js src/react/app.js -t [ babelify --presets [ es2015 react ] ] | node_modules/uglify-js/bin/uglifyjs > src/public/scripts/bundled.js"
   },
   "repository": {
     "type": "git",
@@ -56,7 +56,7 @@
     "redis": "^2.4.2",
     "spin": "0.0.1",
     "sqlite3": "^3.1.1",
-    "uglifyjs": "^2.4.10",
+    "uglify-js": "^2.4.10",
     "vision": "^4.0.1",
     "winston": "^2.1.1"
   },
diff --git a/src/config/default.yml b/src/config/default.yml
index fab6d51..c72b55d 100644
--- a/src/config/default.yml
+++ b/src/config/default.yml
@@ -8,4 +8,4 @@ Defaults:
       Language: en
     Dynamo:
       Table: consigliere
-      Region: ap-southeast-2
+      Region: us-east-1
```

Ah! Just a last tip... I run everything without super user (as it seems to be Node's default modus operandi) and to start the server, used

```
sudo PORT=80 REDIS_URL=redis://redis-dns:6379/1 ~/.nvm/versions/node/v4.4.5/bin/npm start
```

Right from the git's path... Don't know if it's a bad practice, tho :)
Hope it helps.

--
[1] starting from `src/lib/statfetcher.js +20`, then found `node_modules/redis/lib/createClient.js +6` and its implementation. On line `28` you have the conn pattern :)
[2] used my browser's network inspector... they where all 404'ing :O
[3] both lines 10 and 56 on the `package.js`, you may want to change it on dev dependencies as well, but I kept it short here...
